-- Copy dan paste script ini di SQL Editor Supabase kamu

-- 1. Buat tabel activities
create table activities (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null,
  distance float8 not null default 0,
  duration int4 not null default 0,
  pace text,
  route_path jsonb,
  start_time timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users default auth.uid()
);

-- 2. Enable Row Level Security (RLS)
alter table activities enable row level security;

-- 3. Policy: User hanya bisa melihat datanya sendiri
create policy "User can see own data"
  on activities for select
  using (auth.uid() = user_id);

-- 4. Policy: User hanya bisa insert datanya sendiri
create policy "User can insert own data"
  on activities for insert
  with check (auth.uid() = user_id);

-- CATATAN:
-- Ambil URL dan ANON KEY dari Project Settings -> API
-- Masukkan ke file .env di project lokalmu.
