-- Copy dan paste script ini di SQL Editor Supabase kamu

-- 1. Buat tabel relationships (Follow/Unfollow)
create table relationships (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  follower_id uuid references auth.users not null,
  following_id uuid references auth.users not null,
  constraint unique_follow unique (follower_id, following_id) -- Mencegah follow dobel
);

-- 2. Enable RLS
alter table relationships enable row level security;

-- 3. Policy: Public can read relationships (Biar bisa hitung followers)
create policy "Public can read relationships"
  on relationships for select
  using ( true );

-- 4. Policy: User can specific INSERT (Follow)
create policy "User can follow others"
  on relationships for insert
  with check ( auth.uid() = follower_id );

-- 5. Policy: User can specific DELETE (Unfollow)
create policy "User can unfollow others"
  on relationships for delete
  using ( auth.uid() = follower_id );
